### ISSUE TITLE
Show library license

### ISSUE THREAD

**Issue by s-celles** [njh/arduino-libraries#5]
Hello,

Arduino libraries should display library license
Related issue https://github.com/arduino/Arduino/issues/6646

Kind regards

**Comment by njh** [comment]
Is this dependant on it appearing in the Library Manager JSON?

Or are you asking me to do the license detection myself?

**Comment by scls19fr** [comment]
My opinion is that it should be managed upstream ie in Arduino JSON http://downloads.arduino.cc/libraries/library_index.json

But if you are able to autodetect license it could help to fix upstream issue.

Unfortunately several problems are linked...

The more problematic being https://github.com/arduino/Arduino/issues/7591

I opened this issue just to inform you about current situation...

**Comment by njh** [comment]
Added licence to each of the the library pages in 205d328ffed5cf6a81bbb9beecbed78f9622f0fe.

Currently waiting for the site to rebuild.

**Comment by scls19fr** [comment]
https://www.arduinolibraries.info/libraries/embedded-template-library license is not recognised.
https://github.com/ETLCPP/etl have a LICENSE file which shows it's MIT licensed.

**Comment by scls19fr** [comment]
https://github.com/ETLCPP/etl/search?q=LICENSE

**Comment by njh** [comment]
This ticket is about the rendering of the information, not the detection of licenses.

The ETLCPP license file isn't being detected by GitHub. I am not sure how the GitHub license detector works but it is probably due to customisations in the LICENSE file - it might be the links that have been added after the copyright line.

When a license is detected by GitHub, then it displays in the bar at the top of the project:
![screenshot 2018-05-29 08 57 45](https://user-images.githubusercontent.com/38734/40645579-ad18c18a-631e-11e8-8908-e8d54de53768.png)


The only other change I am planning to make it adding the license to the Linked Data.

**Comment by scls19fr** [comment]
Thanks @njh
